# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daniel Szogyenyi
tagline: powered by curiosity and coffee
icon: /assets/favicon.png
lang: en
author: {name: Daniel Szogyenyi, url: "https://szogyenyid.github.io/"}
tags_path: /tags/
categories_path: /categories/
google_analytics: G-MPFCMD4MVH
paginate: 3
paginate_path: "/p:num/"
disqus: szogyenyid
google_site_verification: l78-uzYf7kerW-onnwE6iDMFszAokZoxn2rcPAOIPRM
description: The blog of Daniel Szogyenyi. Posts about PHP, privacy, and any random thought from his mind.

# Build settings
# theme: minima
remote_theme: szogyenyid/monophase@main
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag 
  - jekyll-paginate
# Exclude from processing
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
